# Generated by Django 4.2 on 2023-05-17 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0004_alter_profile_phone"),
        ("engine", "0004_alter_aimodel_description_alter_dataset_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="panel.profile",
            ),
        ),
    ]
