# Generated by Django 4.2 on 2023-06-11 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AiModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Test-dataset", max_length=25)),
                ("description", models.TextField(blank=True, default=None)),
                (
                    "framework",
                    models.CharField(
                        choices=[("Keras", "Keras"), ("Pytorch", "Pytorch")],
                        default="Keras",
                        max_length=10,
                    ),
                ),
                (
                    "approach",
                    models.CharField(
                        choices=[("DL", "Deep Learning"), ("ML", "Machine Learning")],
                        default="ML",
                        max_length=20,
                    ),
                ),
                (
                    "model",
                    models.FileField(default=None, upload_to="models/Ai/%Y/%m/%d/"),
                ),
                ("accuracy", models.FloatField(default=0.0)),
                ("precision", models.FloatField(default=0.0)),
                ("recall", models.FloatField(default=0.0)),
                ("private", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default=None, max_length=200)),
                ("abstract", models.TextField(default=None)),
                ("published_year", models.IntegerField(default=None)),
                ("doi", models.CharField(default=None, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=25)),
                ("description", models.TextField(blank=True, default=None)),
                (
                    "type",
                    models.CharField(
                        choices=[("EEG", "EEG"), ("fMRI", "fMRI")],
                        default="EEG",
                        max_length=10,
                    ),
                ),
                (
                    "research_field",
                    models.CharField(
                        choices=[("MI", "Motor Imagery"), ("ERP", "ERP")],
                        default="MI",
                        max_length=20,
                    ),
                ),
                (
                    "dataset_link",
                    models.URLField(default="https://google.com", null=True),
                ),
                ("dataset_path", models.CharField(max_length=256, null=True)),
                ("private", models.BooleanField(default=False)),
                (
                    "related_models",
                    models.ManyToManyField(
                        blank=True, default=None, to="demoapp.aimodel"
                    ),
                ),
                (
                    "related_paper",
                    models.ManyToManyField(
                        blank=True, default=None, to="demoapp.paper"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="aimodel",
            name="related_dataset",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="demoapp.dataset"
            ),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="related_paper",
            field=models.ManyToManyField(default=None, to="demoapp.paper"),
        ),
    ]
