# Generated by Django 4.2 on 2023-07-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0007_request_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="request",
            old_name="model",
            new_name="ai_model",
        ),
    ]
