# Generated by Django 4.2 on 2023-07-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0009_remove_request_ai_model_remove_request_dataset_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="user",
        ),
    ]
