# Generated by Django 4.2 on 2023-07-11 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0004_alter_profile_phone"),
        ("demoapp", "0010_remove_request_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demo_request",
                to="panel.profile",
            ),
        ),
        migrations.RemoveField(
            model_name="request",
            name="ai_model",
        ),
        migrations.RemoveField(
            model_name="request",
            name="dataset",
        ),
        migrations.AddField(
            model_name="request",
            name="ai_model",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="demoapp.aimodel",
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="dataset",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="demoapp.dataset",
            ),
        ),
    ]
