# Generated by Django 4.2 on 2023-07-12 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0013_alter_request_end_time_alter_request_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 12, 16, 53, 54, 29270), null=True
            ),
        ),
    ]
