# Generated by Django 4.2 on 2023-07-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0014_alter_request_end_time_alter_request_start_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="request",
            name="start_time",
        ),
    ]
