# Generated by Django 4.2 on 2023-07-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0004_alter_profile_phone"),
        ("demoapp", "0015_remove_request_end_time_remove_request_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="user",
            field=models.ManyToManyField(
                related_name="dem_request", to="panel.profile"
            ),
        ),
    ]
