# Generated by Django 4.2 on 2023-07-12 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0004_alter_profile_phone"),
        ("demoapp", "0016_alter_request_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 12, 16, 59, 9, 287656), null=True
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="user",
            field=models.ManyToManyField(
                related_name="demo_request", to="panel.profile"
            ),
        ),
    ]
