# Generated by Django 4.2 on 2023-07-12 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0018_remove_request_ai_model_remove_request_dataset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="request",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 12, 17, 8, 13, 912739), null=True
            ),
        ),
    ]
