# Generated by Django 4.2 on 2023-07-15 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0021_remove_request_eeg_chan_remove_request_eog_chan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="EEG_Chan",
            field=models.CharField(default=[], max_length=20),
        ),
        migrations.AddField(
            model_name="request",
            name="EOG_Chan",
            field=models.CharField(
                default=["EOG:ch01", "EOG:ch02", "EOG:ch03"], max_length=20
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="baseline",
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name="request",
            name="event_id",
            field=models.CharField(default=[10, 11], max_length=30),
        ),
        migrations.AddField(
            model_name="request",
            name="exclude",
            field=models.CharField(default="bads", max_length=20),
        ),
        migrations.AddField(
            model_name="request",
            name="filter",
            field=models.CharField(
                choices=[(False, "None"), ("Bandpass", "Bandpass")],
                default=False,
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="high_band",
            field=models.FloatField(default=30.0),
        ),
        migrations.AddField(
            model_name="request",
            name="low_band",
            field=models.FloatField(default=7.0),
        ),
        migrations.AddField(
            model_name="request",
            name="montage",
            field=models.CharField(
                choices=[
                    (False, "None"),
                    ("standard_1005", "standard_1005"),
                    ("standard_1020", "standard_1020"),
                ],
                default=False,
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="projection",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="request",
            name="test_size",
            field=models.FloatField(default=0.3, max_length=5),
        ),
        migrations.AddField(
            model_name="request",
            name="tmax",
            field=models.FloatField(default=4, max_length=5),
        ),
        migrations.AddField(
            model_name="request",
            name="tmin",
            field=models.FloatField(default=-1, max_length=5),
        ),
        migrations.AlterField(
            model_name="request",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 15, 15, 51, 2, 982793), null=True
            ),
        ),
    ]
