# Generated by Django 4.2 on 2023-07-15 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0023_alter_request_baseline_alter_request_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="Stim_Chan",
            field=models.CharField(default=[], max_length=20),
        ),
        migrations.AddField(
            model_name="request",
            name="event_from",
            field=models.CharField(
                choices=[("Annotations", "annotations"), ("Stim", "stim")],
                default="Annotations",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 15, 15, 59, 53, 979813), null=True
            ),
        ),
    ]
