# Generated by Django 4.2 on 2023-07-15 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0025_request_montage_type_request_on_missing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="EEG_Chan",
            field=models.CharField(default=[], max_length=200),
        ),
        migrations.AlterField(
            model_name="request",
            name="EOG_Chan",
            field=models.CharField(
                default=["EOG:ch01", "EOG:ch02", "EOG:ch03"], max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="Stim_Chan",
            field=models.CharField(default=[], max_length=100),
        ),
        migrations.AlterField(
            model_name="request",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 15, 16, 7, 28, 373921), null=True
            ),
        ),
    ]
