# Generated by Django 4.2 on 2023-07-15 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0026_alter_request_eeg_chan_alter_request_eog_chan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="event_from",
            field=models.CharField(
                choices=[("annotations", "annotations"), ("stim", "stim")],
                default="Annotations",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 15, 16, 12, 58, 695265), null=True
            ),
        ),
    ]
