# Generated by Django 4.2 on 2023-07-15 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0027_alter_request_event_from_alter_request_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="EEG_Chan",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="request",
            name="EOG_Chan",
            field=models.CharField(
                default="'EOG:ch01', 'EOG:ch02', 'EOG:ch03'", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="Stim_Chan",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="request",
            name="event_id",
            field=models.CharField(default="10,11", max_length=30),
        ),
        migrations.AlterField(
            model_name="request",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 15, 16, 20, 7, 11834), null=True
            ),
        ),
    ]
