# Generated by Django 4.2 on 2023-07-17 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0029_request_output_shape_alter_request_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="model",
            field=models.FileField(blank=True, default=None, upload_to="Ai_models/"),
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="name",
            field=models.CharField(default="Test-dataset", max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="EEG_Chan",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="request",
            name="Stim_Chan",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="request",
            name="filter",
            field=models.CharField(
                choices=[(False, "None"), ("Bandpass", "Bandpass")],
                default="Bandpass",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 17, 17, 22, 38, 501847), null=True
            ),
        ),
    ]
