# Generated by Django 4.2 on 2023-07-24 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0032_aimodel_results_json_alter_request_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="request_id_hash",
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name="request",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 24, 16, 53, 28, 109004), null=True
            ),
        ),
    ]
