# Generated by Django 4.2 on 2023-07-26 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0033_request_request_id_hash_alter_request_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 26, 17, 1, 37, 259212), null=True
            ),
        ),
    ]
