# Generated by Django 4.2 on 2023-07-26 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0035_remove_aimodel_related_dataset_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="name",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="request",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 26, 17, 19, 33, 188745), null=True
            ),
        ),
    ]
