# Generated by Django 4.2 on 2023-09-02 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0042_alter_request_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="trained_model",
            field=models.FilePathField(blank=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 2, 12, 30, 58, 343545), null=True
            ),
        ),
    ]
