# Generated by Django 4.2 on 2023-09-02 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0043_request_trained_model_alter_request_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 2, 12, 35, 11, 62780), null=True
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="trained_model",
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
