# Generated by Django 4.2 on 2023-09-02 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0044_alter_request_start_time_alter_request_trained_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="trained_model",
        ),
        migrations.AlterField(
            model_name="request",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 2, 12, 36, 31, 500848), null=True
            ),
        ),
    ]
