# Generated by Django 4.2 on 2023-09-02 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0045_remove_request_trained_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="trained_model",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="request",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 2, 12, 39, 40, 946137), null=True
            ),
        ),
    ]
