# Generated by Django 4.2 on 2023-05-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0002_alter_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(default="09100366857", max_length=15),
        ),
    ]
