# Generated by Django 4.2 on 2023-05-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0003_profile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(default="+9890000000000", max_length=15),
        ),
    ]
